# Generated by Django 5.1.3 on 2024-12-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='desc',
            field=models.CharField(default='hello', max_length=1000),
        ),
        migrations.AlterField(
            model_name='games',
            name='rating',
            field=models.FloatField(),
        ),
    ]
